name:                wxhs-test
version:             0.1.0.0
github:              theindigamer/wxhs-test
license:             BSD3
author:              Varun Gandhi
maintainer:          theindigamer15@gmail.com
copyright:           2017 Varun Gandhi

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:
# description:
# category:            Web

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wxhs-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # -threaded
    # -rtsopts
    # -with-rtsopts=-N
    dependencies:
    - wxhs-test
    - wx
    - wxcore
    - reactive-banana >= 1.0 && < 2
    - reactive-banana-wx >= 1.0 && < 2

tests:
  wxhs-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wxhs-test
